# Generated by Django 6.0.5 on 2026-05-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_funcionario_cpf_remove_funcionario_idade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
    ]
