# Generated by Django 6.0.5 on 2026-05-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_remove_funcionario_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='1111', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='idade',
            field=models.IntegerField(default='22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='2222222', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('caixa', 'Caixa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
