# Generated by Django 6.0.5 on 2026-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
