# Generated by Django 6.0.5 on 2026-05-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_itemvenda_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='subtotal',
            new_name='preco',
        ),
    ]
